### ISSUE TITLE
Font in modeline

### ISSUE THREAD

**Issue by priyadarshan** [jwiegley/dot-emacs#10]
I have been trying (and studying) your .emacs.d. It is wonderfully fast! After cloning with `git clone  --recursive https://github.com/jwiegley/dot-emacs .emacs.d` I seem to have all the requirements (beside a missing mail checking app).

I have also enabled the font Source Pro, and Myriad Pro, as in `init.el`. Still, it seems I am missing one font:

![screen shot 2015-05-17 at 18 00 16](https://cloud.githubusercontent.com/assets/1652143/7671113/00f41c24-fcbf-11e4-9ebc-2ffc991bb7b7.png)

Which font is that one?

Thank you for your code! Really instructive.

**Comment by jwiegley** [comment]
Huh, I thought I was only using a single font actually.

And your comment makes me realize that I should probably have a "scripts" directory in the repository containing all the scripts my configuration depends on.

**Comment by priyadarshan** [comment]
Thanks, that would be nice!

**Comment by priyadarshan** [comment]
Since you were mentioning a "scripts" directory, I see this almost at the beginning of init.el:

```
(defsubst nix-lisp-path (part)
  (expand-file-name part "~/.nix-profile/share/emacs/site-lisp"))
```
May I know what kind of libraries would be there?

I can desume the logical functions of `site-lisp`, `lib`, `override`. Is there a practical need to have separate libraries in `.nix-profile/share/emacs/site-lisp` as well?

I can see your setup is quite flexible, and I would like to understand better its modularity.

By the way, I have been testing quite a few `.emacs.d`'s and yours is by far the fastest, while being very much feature-full.

Thank you for sharing it, I am learning so much from studying it.

**Comment by jwiegley** [comment]
>>>>> Priyadarshan  <notifications@github.com> writes:

> (defsubst nix-lisp-path (part)
>   (expand-file-name part "~/.nix-profile/share/emacs/site-lisp"))
> May I know what kind of libraries would be there?

Those are packages installed using Nix, rather than installed by hand.  I
rarely install such packages, but do for a few large things like AucTeX.

> By the way, I have been testing quite a few .emacs.d's and yours is by far
> the fastest, while being very much feature-full.
>
> Thank you for sharing it, I am learning so much from studying it.

Thanks nice to hear, thank you!

John
