### ISSUE TITLE
Dired+. Is it possible to change color of recent created/edit files/folders?

### ISSUE THREAD

**Issue by lmdic** [jwiegley/dot-emacs#15]
Windows 10, Emacs 25.1, Dired+

I use file manager Total Commander. And I set them to show different color (blue) for recent created/edited files/folder. It's very comfortably.

Here example:

![tc_new_foleder_change_color](https://user-images.githubusercontent.com/303539/31770567-3728b1ba-b4e1-11e7-9cd4-ef229e356c03.png)

Is it possible in Emacs in Dired+ mode?

**Comment by jwiegley** [comment]
I don't know, you'll have to ask the dired+ author!
