### ISSUE TITLE
agenda background color according to file/category

### ISSUE THREAD

**Issue by novoid** [jwiegley/dot-emacs#20]
Hi,

Thanks for the insight of your September talk, [I watched it very closely to learn](https://karl-voit.at/2019/10/26/all-things-org/) how you're dealing with everyday org issues I also do face too well.

I just studied your repo here but could not find out how you are applying **different background colors to complete lines within your agenda (only) according to the file/category**. 

- `org-tag-faces` -> only tags
- `org-todo-keyword-faces` -> [only keywords](https://orgmode.org/manual/Faces-for-TODO-keywords.html)

So how are you accomplishing this?

Thanks for your time!

**Comment by jwiegley** [comment]
I use this function:

https://github.com/jwiegley/dot-emacs/blob/master/dot-org.el#L126

You can see that later I call:

```lisp
(add-hook 'org-finalize-agenda-hook 'org-agenda-add-overlays)
```

And then I have this in, for example, `todo.org`:

```
* Inbox
:PROPERTIES:
:CATEGORY: Inbox
:OVERLAY:  (face (:background "#E444CC" :foreground "#FFFFFF"))
:ID:       DB5226DB-93BD-4FDC-89C6-0DBE5D1A607E
:END:
```

**Comment by novoid** [comment]
Ah, so you need at least one parent heading that contains the drawer with the overlay setting. I'll try to include this to my agenda as well.

Thanks for your explanation!
