### ISSUE TITLE
`'after-init-hook` question

### ISSUE THREAD

**Issue by rajivr** [jwiegley/dot-emacs#23]
Hi John, I was wondering if there was some reason for quasi-quoting the function that is passed to `'after-init-hook` in `init.el`?

```elisp
(add-hook 'after-init-hook
          `(lambda ()
             (setq file-name-handler-alist file-name-handler-alist-old
                   gc-cons-threshold 800000
                   gc-cons-percentage 0.1)
             (garbage-collect)) t)
```

**Comment by jwiegley** [comment]
No reason at all, maybe there was an interpolate variable there at some point in the past? I'll clean it up.
