### ISSUE TITLE
Are you still using the M-x customize interface?

### ISSUE THREAD

**Issue by gamb** [jwiegley/dot-emacs#25]
Hi John!

I noticed in your recent move to a literate configuration you now store customisations in `:custom` rather than a blob of settings inside `custom-set-variables`.

I'd like to do the same but the thing that prohibits me is I still like to use `M-x customize-variable` quite a lot and as far as I know there isn't a package that will route these to the applicable `:custom` block, something like the way you described here https://github.com/jwiegley/use-package/issues/517#issuecomment-347630060

Did you find a solution to this or did you just adapt your workflow?

**Comment by gamb** [comment]
I'm now wondering if I actually would rather a customize-style interface _for_ the use-package macro… A bit of work 😅

**Comment by jwiegley** [comment]
I just adapted. I still use customize, but after it writes the changes out to `settings.el`, I then manually copy the result into my `init.org` file.
