### ISSUE TITLE
bbdb-vcard-export record name change

### ISSUE THREAD

**Issue by henrylaxen** [jwiegley/dot-emacs#8]
Dear John,

While reading the page on the emacswiki: http://www.emacswiki.org/emacs/BbdbExporters I saw your comment saying: "I’ve ported this module to BBDB 3. – JohnWiegley"  Keeping to the adage that no good deed shall go unpunished, I installed it in my spanking new arch linux system.  However it crashed when I tried to use it.  The latest bbdb which I installed via melpa (Version: 20131116.930) seems to have changed the name of the function bbdb-record-note to bbdb-record-xfield.  Here is the diff that got it to work once again:

```
 130c130
 <         (notes (bbdb-record-xfield record 'note))
 ---
 >         (notes (bbdb-record-note record 'note))
 134c134
 <         (categories (bbdb-record-xfield record 'category)))
 ---
 >         (categories (bbdb-record-note record 'category)))
```

It is easily achieved by doing a query-replace bbdb-record-note -> bbdb-record-xfield

I hope this is helpful.

Best wishes,
Henry Laxen

**Comment by jwiegley** [comment]
@henrylaxen Thanks for letting me know!

**Comment by jwiegley** [comment]
I believe this is no longer an issue, correct?
